export const GET_TOKEN = 'GET_TOKEN'; 
export const GET_SESSION_ID = 'GET_SESSION_ID';

export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_MOVIE = 'GET_MOVIE';
export const GET_FILTERED_MOVIES = 'GET_FILTERED_MOVIES';
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const GET_FAVORITE_MOVIES = 'GET_FAVORITE_MOVIES';

export const GET_LAYOUT_TYPE = 'GET_LAYOUT_TYPE';
export const PAGINTATION = 'PAGINTATION';
export const SET_SORT_PARAM = 'SET_SORT_PARAM';
export const SET_SEARCH_STRING = 'SET_SEARCH_STRING';
export const CLEAN_UP_MOVIE_LISTS = 'CLEAN_UP_MOVIE_LISTS';